- name: Read Server Kubeconfig
  become: yes
  hosts: all
  tasks:
    - name: Read k3s kubeconfig
      ansible.builtin.slurp:
        path: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_raw

    - name: Parse kubeconfig
      ansible.builtin.set_fact:
        kubeconfig: "{{ kubeconfig_raw.content | b64decode | from_yaml }}"

    - name: Extract Terraform vars
      ansible.builtin.set_fact:
        tf_k8s_host: "{{ kubeconfig.clusters[0].cluster.server }}"
        tf_k8s_cluster_ca_certificate: "{{ kubeconfig.clusters[0].cluster['certificate-authority-data'] }}"
        tf_k8s_client_certificate: "{{ kubeconfig.users[0].user['client-certificate-data'] }}"
        tf_k8s_client_key: "{{ kubeconfig.users[0].user['client-key-data'] }}"

    - debug:
        msg: "TF_K8S_CLUSTER_CA_CERTIFICATE={{tf_k8s_cluster_ca_certificate}}"

    - debug:
        msg: "TF_K8S_CLIENT_CERTIFICATE={{tf_k8s_client_certificate}}"

    - debug:
        msg: "TF_K8S_CLIENT_KEY={{tf_k8s_client_key}}"
