
- name: Read Server Kubeconfig
  become: yes
  hosts: all
  tasks:
    - name: Install NFS client
      apt:
        name: nfs-common
        state: present
        update_cache: yes
    - name: Create mount directory
      file:
        path: /mnt/k8s
        state: directory
    - name: Mount TrueNAS NFS share
      mount:
        path: /mnt/nfs
        src: "truenas.lan:/mnt/pool/k8s"
        fstype: nfs
        opts: "defaults,nofail"
        state: mounted
